### PR TITLE
Update spatial_utils.py

### PR DESCRIPTION
**Pull request by davidshumway**
Improve distance calculation and adjacency matrix

### CODE REVIEW

**Comment by konstantinklemmer** [comment]
Hi @davidshumway! Thanks for this - in general I would like to keep this repository as unchanged as possible so the exact originally published code is here, but your changes are generally minor so I am happy to adapt them. 

However, there is one issue with the code:

```
def knn_to_adj(knn, n):
  adj_matrix = torch.zeros(n, n, dtype=float) #lil_matrix((n, n), dtype=float) 
  for i in range(len(knn[0])):
    tow = knn[0][i]
    fro = knn[1][i]
    adj_matrix[tow,fro] = 1 # should be bidectional?
  return adj_matrix.T
```

is not equivalent with

```
def knn_to_adj(knn, n):
  return to_dense_adj(knn).squeeze()
```

because `to_dense_adj` expects the node pairs in flipped order. The correct definition would be 

```
def knn_to_adj(knn, n):
  return to_dense_adj(knn.flip(0)).squeeze()
```

Can you change that in your PR? Then I can merge.

**Comment by davidshumway** [comment]
> Hi @davidshumway! Thanks for this - in general I would like to keep this repository as unchanged as possible so the exact originally published code is here, but your changes are generally minor so I am happy to adapt them.
> However, there is one issue with the code:
> 
> ```
> def knn_to_adj(knn, n):
>   adj_matrix = torch.zeros(n, n, dtype=float) #lil_matrix((n, n), dtype=float) 
>   for i in range(len(knn[0])):
>     tow = knn[0][i]
>     fro = knn[1][i]
>     adj_matrix[tow,fro] = 1 # should be bidectional?
>   return adj_matrix.T
> ```
> 
> is not equivalent with
> 
> ```
> def knn_to_adj(knn, n):
>   return to_dense_adj(knn).squeeze()
> ```
> 
> because `to_dense_adj` expects the node pairs in flipped order. The correct definition would be
> 
> ```
> def knn_to_adj(knn, n):
>   return to_dense_adj(knn.flip(0)).squeeze()
> ```
> 
> Can you change that in your PR? Then I can merge.

Sounds good.

**Comment by konstantinklemmer** [comment]
Cool, thanks! Is this good to go from your side @davidshumway?

**Comment by davidshumway** [comment]
Yes @konstantinklemmer

**Review by konstantinklemmer — APPROVED** [review]

**Comment by konstantinklemmer** [comment]
Merge improvements to distance calculation.

**Pull request merged**
